# Generated by Django 4.1.1 on 2022-09-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('grade', models.CharField(blank=True, max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
