# Generated by Django 4.1.1 on 2022-09-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_information_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information',
            new_name='Details',
        ),
    ]
