# Generated by Django 4.1.1 on 2022-09-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_information_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Information',
        ),
    ]
