# Generated by Django 4.1 on 2022-08-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_animalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.familyprofile'),
        ),
    ]
