# Generated by Django 4.1 on 2022-09-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activities',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='places_to_visit',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='restaurants',
            field=models.CharField(max_length=1000),
        ),
    ]
