# Generated by Django 4.1 on 2022-09-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('activity', '0004_alter_activity_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
    ]
